### ISSUE TITLE
Implement DeviceDAO

### ISSUE THREAD

**Issue by rehand** [rehand/QRdmin#3]
Implement the DeviceDAO in order to store and retrieve Device objects from the server backend.

The DeviceDAO should offer the following methods:
- retrieve([id])
- save([Device])

It is responsible for parsing JSON and create a Device object out of it an vice versa.

The URL of the server can be hard coded in the first step (at some point later it could be moved to the settings of the app).

**Comment by go-ive** [comment]
url is still hard coded, i'll make a new task to change this
